CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Oil - Sesame', 733.65);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Wine - Sauvignon Blanc Oyster', 340.2);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Glaze - Clear', 650.46);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Rice - Basmati', 55.59);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Vector Energy Bar', 921.48);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Sobe - Liz Blizz', 236.31);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Pork - Bones', 966.06);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beef - Bones, Cut - Up', 518.38);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Snapple - Mango Maddness', 125.22);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Arctic Char - Fillets', 34.85);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Butter - Unsalted', 75.1);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Yoghurt Tubes', 789.54);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Contreau', 23.02);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Cheese Cloth', 83.58);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Wine - Magnotta - Pinot Gris Sr', 497.6);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Mushroom - Portebello', 486.87);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Filo Dough', 500.06);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Capon - Breast, Wing On', 32.56);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beef - Rib Eye Aaa', 133.67);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Pastry - Banana Muffin - Mini', 888.24);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Rye Special Old', 274.51);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Devonshire Cream', 110.19);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Lemonade - Island Tea, 591 Ml', 940.39);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beef - Tenderloin', 290.98);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Cheese - Goat', 743.81);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Stock - Beef, White', 977.28);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Kellogs Cereal In A Cup', 597.53);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Plasticspoonblack', 729.53);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Lettuce - Treviso', 1.22);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Alize Gold Passion', 53.52);
