/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;
import model.validations.UserDataValidations;
import ficheros.ClassFichero;
import java.io.FileNotFoundException;
/**
 *
 * @author gerardgomazn
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        initConfig();
        //ClassFichero.createFile("user_data_tusIniciales.csv");
    }
    private void initConfig(){
        jButtonValidateActionPerformed.setEnabled(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        csv = new javax.swing.JPanel();
        jLabel1Title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelNIF = new javax.swing.JLabel();
        jTextFieldNIF = new javax.swing.JTextField();
        jButtonValidateActionPerformed = new javax.swing.JButton();
        jLabelErrorName = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelBirthdate = new javax.swing.JLabel();
        jTextFieldBirthdate = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jLabelAge = new javax.swing.JLabel();
        jTextFieldZip = new javax.swing.JTextField();
        jLabelZip = new javax.swing.JLabel();
        jLabelErrorNif = new javax.swing.JLabel();
        jLabelErrorEmail = new javax.swing.JLabel();
        jLabelErrorBirthdate = new javax.swing.JLabel();
        jLabelErrorAge = new javax.swing.JLabel();
        jLabelErrorZip = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1-88140682.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1Title.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1Title.setForeground(new java.awt.Color(255, 51, 204));
        jLabel1Title.setText("VALIDADOR DATOS USUARIOS");
        jLabel1Title.setToolTipText("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1-88140682.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setText("NAME");

        jLabelNIF.setText("NIF");

        jButtonValidateActionPerformed.setText("Validar");
        jButtonValidateActionPerformed.setBorderPainted(false);
        jButtonValidateActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidateActionPerformedActionPerformed(evt);
            }
        });

        jLabelErrorName.setForeground(new java.awt.Color(255, 0, 0));

        jLabelEmail.setText("Email");

        jLabelBirthdate.setText("Birthdate");

        jTextFieldAge.setEditable(false);
        jTextFieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgeActionPerformed(evt);
            }
        });

        jLabelAge.setText("Age");

        jLabelZip.setText("Zip");

        jLabelErrorNif.setForeground(new java.awt.Color(255, 51, 51));

        jLabelErrorEmail.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrorBirthdate.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrorAge.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrorZip.setForeground(new java.awt.Color(255, 0, 0));

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("csv");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout csvLayout = new javax.swing.GroupLayout(csv);
        csv.setLayout(csvLayout);
        csvLayout.setHorizontalGroup(
            csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csvLayout.createSequentialGroup()
                .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(csvLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(csvLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelErrorName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(csvLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(csvLayout.createSequentialGroup()
                                .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNIF)
                                    .addComponent(jLabelEmail)
                                    .addComponent(jLabelBirthdate)
                                    .addComponent(jLabelAge)
                                    .addComponent(jLabelZip))
                                .addGap(18, 18, 18)
                                .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(csvLayout.createSequentialGroup()
                                        .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelErrorNif, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(csvLayout.createSequentialGroup()
                                        .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelErrorAge, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(csvLayout.createSequentialGroup()
                                        .addComponent(jTextFieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelErrorZip, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(csvLayout.createSequentialGroup()
                                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabelErrorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(csvLayout.createSequentialGroup()
                                            .addComponent(jTextFieldBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelErrorBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(csvLayout.createSequentialGroup()
                                .addComponent(jButtonValidateActionPerformed)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        csvLayout.setVerticalGroup(
            csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csvLayout.createSequentialGroup()
                .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(csvLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(csvLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelErrorName))
                .addGap(48, 48, 48)
                .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorNif, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNIF)))
                .addGap(45, 45, 45)
                .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelEmail)))
                .addGap(45, 45, 45)
                .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthdate)
                    .addComponent(jLabelErrorBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelAge)))
                .addGap(42, 42, 42)
                .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZip)
                    .addComponent(jTextFieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorZip, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValidateActionPerformed)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(760, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(csv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(csv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1334, 1334, 1334))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidateActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidateActionPerformedActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldName.getText();
        if (UserDataValidations.checkName(name) == false){
            jLabelErrorName.setText("Incorrect Name!");
        }
        String nif = jTextFieldNIF.getText();
        if (UserDataValidations.checkId(1, nif) == false){
            jLabelErrorNif.setText("Incorrect Nif!");
        }
        String email = jTextFieldEmail.getText();
        if (UserDataValidations.checkEmail(email) == false){
            jLabelErrorEmail.setText("Incorrect Email!");
        }
        String birthDate = jTextFieldBirthdate.getText();
        if (UserDataValidations.checkFormatDate(birthDate) == false){
            jLabelErrorBirthdate.setText("Incorrect date!");
        }
        int age = UserDataValidations.CalculateAge(birthDate); 
        jTextFieldAge.setEditable(false);
        if (age == -1) {
            jLabelErrorAge.setText("Fecha inválida. Verifica el formato (DD/MM/YYYY)");
        } else {
            jTextFieldAge.setText(String.valueOf(age));
        }
        
        jTextFieldName.setEditable(false);
        jTextFieldNIF.setEditable(false);
        jTextFieldEmail.setEditable(false);
        jTextFieldEmail.setEditable(false);
        jTextFieldBirthdate.setEditable(false);
        jTextFieldAge.setEditable(false);
        jButton2.setEnabled(true);


    }//GEN-LAST:event_jButtonValidateActionPerformedActionPerformed

    private void jTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextFieldName.setText("");
        jTextFieldNIF.setText("");
        jTextFieldEmail.setText("");
        jTextFieldBirthdate.setText("");
        jTextFieldAge.setText("");
        jTextFieldZip.setText("");
        
        jButtonValidateActionPerformed.setEnabled(true);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = jTextFieldName.getText();
        String nif = jTextFieldNIF.getText();
        String email = jTextFieldEmail.getText();
        String date = jTextFieldBirthdate.getText();
        String zip = jTextFieldZip.getText();
        String age = jTextFieldAge.getText();
        String line = name + ";" + nif + ";" + email + ";" + date + ";" + zip + ";" + age + ";";
        
        ClassFichero.writeFile(line);
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) throws FileNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        ClassFichero.createFile("user_data_GGA.csv");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel csv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonValidateActionPerformed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Title;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelBirthdate;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelErrorAge;
    private javax.swing.JLabel jLabelErrorBirthdate;
    private javax.swing.JLabel jLabelErrorEmail;
    private javax.swing.JLabel jLabelErrorName;
    private javax.swing.JLabel jLabelErrorNif;
    private javax.swing.JLabel jLabelErrorZip;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelZip;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldBirthdate;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldZip;
    // End of variables declaration//GEN-END:variables
}
